# Frame dimension title saveFormat save
Frame	600	The Mandelbrot Set	gif	false	true
# Palette type name size
Palette	Trigonometric	trig	256
# Fractal type xCenter yCenter delta bailout paletteName
Fractal	Mandelbrot	0.01358457	0.65562668	10	2000	trig
#Alternative Palette Types
#Palette	Random	random	256
#Palette	Grayscale	gs	256
#Palette	NICA	nica	256
#Palette	Enumerated	mono	1	255	255	255
